###All users

GET Http://localhost:3000/users

###Create user in dataBase
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "simeon",
  "email": "simeon@example.com",
  "password": "securepass1234"
}

###auth login user

GET http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "simeon@example.com",
  "password": "securepass1234"
}

###Create a article
POST http://localhost:3000/articles/create
Content-Type: application/json

{
  "title": "Hello team",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
  "authorId": 1
}

###find all articles
GET http://localhost:3000/articles

###find article by id
GET http://localhost:3000/articles/1

###delete article 
DELETE http://localhost:3000/articles/2

###update a article
PATCH http://localhost:3000/articles/3
Content-Type: application/json

{
  "title": "Hello canal",
  "content": "Je suis allé aux cours aujourd'hui"
}