###All users

GET Http://localhost:3000/users

###Create user in dataBase
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "john",
  "email": "john@example.com",
  "password": "securepass1234"
}

###auth login user

GET http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "securepass1234"
}

###Create a article
POST http://localhost:3000/articles/create
Content-Type: application/json

{
  "title": "Hello team",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
  "authorId": 1
}

###find all articles
GET http://localhost:3000/articles
